name: deploy to non prod bucket

  on:
    push:
      branches:
        - feature*

  jobs:
    build:
      runs-on: ubuntu-latest
      env:
        BUCKET_NAME: cfst-3457-d63e16918c7e4f886d05e0938-nonprodbucket-mu2fpxg88paw
      steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: configure aws cli
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: {{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret_access_key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: setup node js
          uses: aws-actions/setup-nodejs@v2
          with:
            node version: 14
        - name: build site
          run:
            npm ci
            npm run build
        - name: deploy files to bucket
          run: aws s3 cp public s3://${{ env.BUCKET_NAME }} / -recursive -acl public-read
